import { useState } from 'react'

const GOOGLE_FORM_URL =
  'https://docs.google.com/forms/d/e/1FAIpQLScjDSv-fwIsDhe1oTMTHNx33XmQw2yGnJ4tYx9d4rM0Tiop2g/viewform?embedded=true'

/* ─── DATA ─────────────────────────────────────────── */

const projects = [
  {
    tag: 'Health Monitoring',
    year: '2024',
    title: 'PawTrack Health',
    desc: 'Wearable-connected continuous health monitoring for dogs of all breeds and ages. Tracks heart rate, respiratory patterns, sleep quality, and temperature — sending smart alerts to owners and vets before issues escalate.',
    img: 'https://images.unsplash.com/photo-1602241628512-459cdd3234fe?w=640&h=440&fit=crop&auto=format',
    alt: 'Golden retriever wearing a collar',
  },
  {
    tag: 'Nutrition Planning',
    year: '2024',
    title: 'NutriPaw',
    desc: 'Breed-specific, age-adjusted nutrition plans generated by veterinary dietitians and refined by AI. Tracks daily food intake, flags nutritional gaps, and integrates with popular pet-food delivery services.',
    img: 'https://images.unsplash.com/photo-1658833944717-ce9680d3c4d5?w=640&h=440&fit=crop&auto=format',
    alt: 'Brown dog with green collar looking healthy',
  },
  {
    tag: 'Activity & Care',
    year: '2025',
    title: 'WalkLog',
    desc: 'Automatically logs walks, play sessions, and rest periods using GPS and motion sensors. Gives owners a complete picture of their dog\'s daily activity and flags deviations that may indicate pain or fatigue.',
    img: 'https://images.unsplash.com/photo-1530700131180-d43d9b8cc41f?w=640&h=440&fit=crop&auto=format',
    alt: 'Person walking with a golden retriever',
  },
]

const benefits = [
  {
    icon: '🩺',
    title: 'Early Illness Detection',
    desc: 'Herdwise flags subtle changes in vitals and behaviour up to 48 hours before clinical signs appear — giving vets and owners critical time to intervene.',
  },
  {
    icon: '📊',
    title: 'Lifetime Health Records',
    desc: 'Every vet visit, vaccine, medication, and health event is logged and searchable — one unified timeline that travels with your dog forever.',
  },
  {
    icon: '🌿',
    title: 'Personalised Nutrition',
    desc: 'Breed, age, weight, and activity level all shape your dog\'s daily nutrition plan, updated automatically as their life stage changes.',
  },
  {
    icon: '🏃',
    title: 'Activity Goal Tracking',
    desc: 'Set daily activity targets by breed and health status. Herdwise tracks progress in real time and recommends rest when your dog shows signs of overdoing it.',
  },
  {
    icon: '🔔',
    title: 'Smart Alerts & Reminders',
    desc: 'Never miss a flea treatment, deworming schedule, or annual vaccination. Reminders arrive before they\'re due — not after.',
  },
  {
    icon: '👩‍⚕️',
    title: 'Vet Collaboration Portal',
    desc: 'Share live data and health logs directly with your veterinary team. No printed records, no repeat questions — just faster, better care.',
  },
]

const features = [
  {
    tab: '01 — Smart Wearable',
    title: 'Real-time health, right on the collar',
    body: 'The Herdwise smart tag clips to any standard collar and streams biometric data continuously. Heart rate, respiratory rate, core temperature, and sleep stage are monitored 24 / 7 and processed by on-device edge AI before syncing to the app.',
    note: 'Battery life: 14 days. Water-resistant IPX7. Compatible with Android and iOS. Supports dogs 4 kg and above.',
    img: 'https://images.unsplash.com/photo-1654895716780-b4664497420d?w=760&h=540&fit=crop&auto=format',
    alt: 'Person tenderly holding a dog at a vet clinic',
  },
  {
    tab: '02 — Health Dashboard',
    title: 'Every metric, one clear view',
    body: 'The Herdwise dashboard aggregates biometric streams, activity logs, nutrition data, and vet records into a single timeline. Colour-coded wellness scores make it immediately obvious which dogs need attention — and why.',
    note: 'Available on web, iOS, and Android. Role-based access lets groomers, dog-sitters, and vets each see what they need.',
    img: 'https://images.unsplash.com/photo-1762751923859-3b1057a6fdec?w=760&h=540&fit=crop&auto=format',
    alt: 'Energetic corgi running through a green park',
  },
  {
    tab: '03 — Vet Connect',
    title: 'Your vet always in the loop',
    body: 'Grant your veterinary clinic read or full access to your dog\'s Herdwise profile. They can review historical data before appointments, annotate records after visits, and push medication reminders directly to the owner\'s app.',
    note: 'HIPAA-compliant data sharing. End-to-end encrypted. Audit log available for all access events.',
    img: 'https://images.unsplash.com/photo-1700665537604-412e89a285c3?w=760&h=540&fit=crop&auto=format',
    alt: 'Veterinarian team caring for a dog',
  },
]

const stats = [
  { value: '85K+', label: 'Dogs on platform' },
  { value: '48 hr', label: 'Avg. early alert window' },
  { value: '4.9 ★', label: 'App store rating' },
  { value: '99.7%', label: 'Uptime reliability' },
]

const navLinks = ['Projects', 'Benefits', 'Features', 'Register']

/* ─── ICONS ─────────────────────────────────────────── */

function IconCheck() {
  return (
    <svg width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2.5" viewBox="0 0 24 24">
      <path d="M5 13l4 4L19 7" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function IconArrow() {
  return (
    <svg width="15" height="15" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
      <path d="M14 5l7 7m0 0l-7 7m7-7H3" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

function PawLogo() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="currentColor">
      <ellipse cx="6" cy="6.5" rx="2.5" ry="3.5" />
      <ellipse cx="18" cy="6.5" rx="2.5" ry="3.5" />
      <ellipse cx="3" cy="13" rx="2" ry="3" />
      <ellipse cx="21" cy="13" rx="2" ry="3" />
      <path d="M12 8c-4 0-7 3-7 6 0 2.5 1.5 4 3.5 4.5.8.2 1.5.8 2 1.5h3c.5-.7 1.2-1.3 2-1.5C17.5 18 19 16.5 19 14c0-3-3-6-7-6z" />
    </svg>
  )
}

/* ─── APP ─────────────────────────────────────────── */

export default function App() {
  const [menuOpen, setMenuOpen]   = useState(false)
  const [activeTab, setActiveTab] = useState(0)

  return (
    <div style={{ fontFamily: 'Outfit, sans-serif', backgroundColor: '#faf6f0', color: '#1c1c1e' }}>

      {/* ══ NAVBAR ══════════════════════════════════════ */}
      <header
        style={{
          position: 'fixed', top: 0, left: 0, right: 0, zIndex: 50,
          backgroundColor: 'rgba(250,246,240,0.92)',
          backdropFilter: 'blur(14px)',
          borderBottom: '1px solid rgba(26,74,92,0.1)',
        }}
      >
        <nav style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px', height: 68, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          {/* Brand */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{ width: 38, height: 38, borderRadius: '50%', backgroundColor: '#1a4a5c', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#faf6f0' }}>
              <PawLogo />
            </div>
            <div>
              <div style={{ fontFamily: 'Fraunces, serif', fontWeight: 600, fontSize: 17, color: '#1a4a5c', lineHeight: 1.1 }}>Herdwise</div>
              <div style={{ fontSize: 10, color: '#d4820a', fontWeight: 500, letterSpacing: '0.08em', textTransform: 'uppercase' }}>Animal Wellness</div>
            </div>
          </div>

          {/* Desktop links */}
          <div style={{ display: 'flex', gap: 36, alignItems: 'center' }} className="hidden-mobile">
            {navLinks.map(n => (
              <a key={n} href={`#${n.toLowerCase()}`} className="nav-link" style={{ fontSize: 14, fontWeight: 500, color: '#1c1c1e', textDecoration: 'none' }}>{n}</a>
            ))}
          </div>

          <a
            href="#register"
            className="hidden-mobile"
            style={{
              display: 'inline-flex', alignItems: 'center', gap: 6,
              backgroundColor: '#1a4a5c', color: '#faf6f0',
              padding: '10px 22px', borderRadius: 999, fontSize: 13, fontWeight: 600,
              textDecoration: 'none', transition: 'opacity 0.2s',
            }}
            onMouseEnter={e => (e.currentTarget.style.opacity = '0.85')}
            onMouseLeave={e => (e.currentTarget.style.opacity = '1')}
          >
            Get Started <IconArrow />
          </a>

          {/* Hamburger */}
          <button
            style={{ display: 'none', background: 'none', border: 'none', cursor: 'pointer', color: '#1a4a5c', padding: 4 }}
            className="show-mobile"
            onClick={() => setMenuOpen(v => !v)}
            aria-label="Toggle menu"
          >
            {menuOpen
              ? <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M6 18L18 6M6 6l12 12" /></svg>
              : <svg width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16" /></svg>
            }
          </button>
        </nav>

        {/* Mobile drawer */}
        {menuOpen && (
          <div style={{ padding: '12px 24px 20px', borderTop: '1px solid rgba(26,74,92,0.08)', display: 'flex', flexDirection: 'column', gap: 14 }}>
            {navLinks.map(n => (
              <a key={n} href={`#${n.toLowerCase()}`} onClick={() => setMenuOpen(false)} style={{ fontSize: 15, fontWeight: 500, color: '#1c1c1e', textDecoration: 'none' }}>{n}</a>
            ))}
            <a
              href="#register"
              onClick={() => setMenuOpen(false)}
              style={{ display: 'inline-flex', justifyContent: 'center', backgroundColor: '#1a4a5c', color: '#faf6f0', padding: '11px 20px', borderRadius: 999, fontSize: 13, fontWeight: 600, textDecoration: 'none' }}
            >
              Get Started
            </a>
          </div>
        )}
      </header>

      {/* ══ HERO ════════════════════════════════════════ */}
      <section style={{ position: 'relative', minHeight: '100vh', display: 'flex', alignItems: 'flex-end', paddingTop: 68, overflow: 'hidden' }}>
        <div style={{ position: 'absolute', inset: 0 }}>
          <img
            src="https://images.unsplash.com/photo-1762751923828-60e2f16ada34?w=1600&h=1000&fit=crop&auto=format"
            alt="Corgi running joyfully on a sunny grassy hill"
            style={{ width: '100%', height: '100%', objectFit: 'cover' }}
          />
          <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top, rgba(10,30,38,0.95) 0%, rgba(10,30,38,0.6) 48%, rgba(10,30,38,0.1) 100%)' }} />
        </div>

        <div style={{ position: 'relative', zIndex: 10, maxWidth: 1200, margin: '0 auto', padding: '0 24px 80px', width: '100%' }}>
          <div style={{ maxWidth: 680 }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, backgroundColor: 'rgba(212,130,10,0.2)', border: '1px solid rgba(212,130,10,0.45)', borderRadius: 999, padding: '6px 14px', marginBottom: 24 }}>
              <span style={{ width: 7, height: 7, borderRadius: '50%', backgroundColor: '#f0a030', display: 'inline-block' }} />
              <span style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', color: '#f0a030' }}>Dog Wellness Platform · 2025</span>
            </div>

            <h1 style={{ fontFamily: 'Fraunces, serif', fontSize: 'clamp(42px, 6vw, 76px)', fontWeight: 600, lineHeight: 1.08, color: '#faf6f0', marginBottom: 20 }}>
              Your dog deserves<br />
              <em style={{ fontStyle: 'italic', fontWeight: 300, color: '#d4820a' }}>proactive care.</em>
            </h1>

            <p style={{ fontSize: 18, lineHeight: 1.65, color: 'rgba(250,246,240,0.78)', marginBottom: 36, maxWidth: 520 }}>
              Herdwise is the complete dog wellness system — health monitoring, nutrition planning, activity tracking, and vet collaboration, all in one place.
            </p>

            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 14 }}>
              <a
                href="#register"
                style={{ display: 'inline-flex', alignItems: 'center', gap: 8, backgroundColor: '#d4820a', color: '#fff', padding: '14px 28px', borderRadius: 999, fontSize: 14, fontWeight: 700, textDecoration: 'none', transition: 'transform 0.2s, box-shadow 0.2s' }}
                onMouseEnter={e => { e.currentTarget.style.transform = 'scale(1.04)'; e.currentTarget.style.boxShadow = '0 8px 24px rgba(212,130,10,0.4)' }}
                onMouseLeave={e => { e.currentTarget.style.transform = 'scale(1)'; e.currentTarget.style.boxShadow = 'none' }}
              >
                Register for Free Access <IconArrow />
              </a>
              <a
                href="#features"
                style={{ display: 'inline-flex', alignItems: 'center', gap: 8, border: '1.5px solid rgba(250,246,240,0.38)', color: '#faf6f0', padding: '14px 28px', borderRadius: 999, fontSize: 14, fontWeight: 600, textDecoration: 'none', transition: 'background 0.2s' }}
                onMouseEnter={e => (e.currentTarget.style.background = 'rgba(250,246,240,0.08)')}
                onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
              >
                See Features
              </a>
            </div>
          </div>

          {/* Stat pills */}
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12, marginTop: 56 }}>
            {stats.map(s => (
              <div key={s.label} style={{ display: 'flex', flexDirection: 'column', backgroundColor: 'rgba(250,246,240,0.1)', backdropFilter: 'blur(8px)', border: '1px solid rgba(250,246,240,0.15)', borderRadius: 14, padding: '14px 20px', minWidth: 120 }}>
                <span style={{ fontFamily: 'Fraunces, serif', fontSize: 24, fontWeight: 700, color: '#f0a030', lineHeight: 1 }}>{s.value}</span>
                <span style={{ fontSize: 11, color: 'rgba(250,246,240,0.6)', marginTop: 4, fontWeight: 500 }}>{s.label}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ PROJECTS ════════════════════════════════════ */}
      <section id="projects" style={{ padding: '96px 0', backgroundColor: '#faf6f0' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px' }}>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 16, alignItems: 'flex-end', marginBottom: 16 }}>
            <div style={{ flex: '1 1 380px' }}>
              <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#d4820a', marginBottom: 14 }}>Our Projects</p>
              <h2 style={{ fontFamily: 'Fraunces, serif', fontSize: 'clamp(32px, 4vw, 50px)', fontWeight: 600, color: '#1a4a5c', lineHeight: 1.15 }}>
                Three tools.<br />One healthy dog.
              </h2>
            </div>
            <p style={{ flex: '1 1 320px', fontSize: 15, lineHeight: 1.7, color: '#6b4a2a', maxWidth: 420 }}>
              Each Herdwise project tackles a specific pillar of canine wellness. Together they give you a complete, continuous picture of your dog's health.
            </p>
          </div>

          <div style={{ height: 1, backgroundColor: 'rgba(26,74,92,0.12)', margin: '28px 0 48px' }} />

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 24 }}>
            {projects.map((p, i) => (
              <div key={i} className="card-lift" style={{ backgroundColor: '#fff', borderRadius: 20, overflow: 'hidden', border: '1px solid rgba(26,74,92,0.09)' }}>
                <div className="img-zoom" style={{ height: 220, overflow: 'hidden', backgroundColor: '#e8e0d4' }}>
                  <img src={p.img} alt={p.alt} style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
                </div>
                <div style={{ padding: 24 }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
                    <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.07em', textTransform: 'uppercase', color: '#1a4a5c', backgroundColor: 'rgba(26,74,92,0.1)', borderRadius: 999, padding: '4px 10px' }}>{p.tag}</span>
                    <span style={{ fontSize: 12, fontWeight: 600, color: '#d4820a' }}>{p.year}</span>
                  </div>
                  <h3 style={{ fontFamily: 'Fraunces, serif', fontSize: 22, fontWeight: 600, color: '#1c1c1e', marginBottom: 8 }}>{p.title}</h3>
                  <p style={{ fontSize: 14, lineHeight: 1.65, color: '#6b4a2a' }}>{p.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ BENEFITS ════════════════════════════════════ */}
      <section id="benefits" style={{ padding: '96px 0', backgroundColor: '#1a4a5c' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px' }}>
          {/* Header row */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 32, alignItems: 'end', marginBottom: 64 }}>
            <div>
              <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#d4820a', marginBottom: 14 }}>Why Herdwise</p>
              <h2 style={{ fontFamily: 'Fraunces, serif', fontSize: 'clamp(32px, 4vw, 50px)', fontWeight: 600, color: '#faf6f0', lineHeight: 1.15 }}>
                Built around<br />
                <em style={{ fontStyle: 'italic', fontWeight: 300, color: '#5a8a7a' }}>your dog's whole life</em>
              </h2>
            </div>
            <div>
              <p style={{ fontSize: 15, lineHeight: 1.7, color: 'rgba(250,246,240,0.68)', marginBottom: 28 }}>
                Most pet apps track one thing. Herdwise tracks everything — and connects the dots so small changes don't become big problems.
              </p>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                {stats.map(s => (
                  <div key={s.label} style={{ backgroundColor: 'rgba(250,246,240,0.07)', border: '1px solid rgba(250,246,240,0.1)', borderRadius: 14, padding: '16px 18px' }}>
                    <div style={{ fontFamily: 'Fraunces, serif', fontSize: 26, fontWeight: 700, color: '#d4820a' }}>{s.value}</div>
                    <div style={{ fontSize: 11, color: 'rgba(250,246,240,0.55)', marginTop: 3 }}>{s.label}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Benefits grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 2 }}>
            {benefits.map((b, i) => (
              <div
                key={i}
                className="benefit-row"
                style={{ display: 'flex', gap: 16, padding: '24px 20px', borderRadius: 16, cursor: 'default' }}
              >
                <div style={{ width: 48, height: 48, borderRadius: 14, backgroundColor: 'rgba(212,130,10,0.18)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 22, flexShrink: 0 }}>
                  {b.icon}
                </div>
                <div>
                  <h3 style={{ fontSize: 15, fontWeight: 700, color: '#faf6f0', marginBottom: 5 }}>{b.title}</h3>
                  <p style={{ fontSize: 13, lineHeight: 1.65, color: 'rgba(250,246,240,0.58)' }}>{b.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ FEATURES ════════════════════════════════════ */}
      <section id="features" style={{ padding: '96px 0', backgroundColor: '#faf6f0' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px' }}>
          <div style={{ textAlign: 'center', marginBottom: 56 }}>
            <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#d4820a', marginBottom: 14 }}>Platform Features</p>
            <h2 style={{ fontFamily: 'Fraunces, serif', fontSize: 'clamp(32px, 4vw, 50px)', fontWeight: 600, color: '#1a4a5c', lineHeight: 1.15, marginBottom: 14 }}>
              How Herdwise works
            </h2>
            <p style={{ fontSize: 15, lineHeight: 1.7, color: '#6b4a2a', maxWidth: 460, margin: '0 auto' }}>
              Three layers of intelligence working together — so your dog gets the best possible care every day.
            </p>
          </div>

          {/* Tabs */}
          <div style={{ display: 'flex', gap: 8, marginBottom: 40, overflowX: 'auto', paddingBottom: 4 }}>
            {features.map((f, i) => (
              <button
                key={i}
                onClick={() => setActiveTab(i)}
                style={{
                  flexShrink: 0,
                  padding: '10px 20px',
                  borderRadius: 999,
                  fontSize: 13,
                  fontWeight: 600,
                  border: 'none',
                  cursor: 'pointer',
                  transition: 'all 0.2s',
                  fontFamily: 'Outfit, sans-serif',
                  ...(activeTab === i
                    ? { backgroundColor: '#1a4a5c', color: '#faf6f0' }
                    : { backgroundColor: 'rgba(26,74,92,0.1)', color: '#1a4a5c' }),
                }}
              >
                {f.tab}
              </button>
            ))}
          </div>

          {/* Feature panel */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 40, alignItems: 'center' }}>
            <div className="img-zoom" style={{ borderRadius: 24, overflow: 'hidden', backgroundColor: '#ddd5c8' }}>
              <img
                src={features[activeTab].img}
                alt={features[activeTab].alt}
                style={{ width: '100%', height: 400, objectFit: 'cover', display: 'block', transition: 'all 0.4s' }}
              />
            </div>
            <div style={{ padding: '0 8px' }}>
              <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#d4820a', marginBottom: 12 }}>{features[activeTab].tab}</p>
              <h3 style={{ fontFamily: 'Fraunces, serif', fontSize: 'clamp(26px, 3vw, 38px)', fontWeight: 600, color: '#1a4a5c', lineHeight: 1.2, marginBottom: 18 }}>
                {features[activeTab].title}
              </h3>
              <p style={{ fontSize: 15, lineHeight: 1.72, color: '#6b4a2a', marginBottom: 24 }}>
                {features[activeTab].body}
              </p>

              <div style={{ display: 'flex', gap: 8, alignItems: 'flex-start', padding: '16px 18px', backgroundColor: 'rgba(26,74,92,0.06)', border: '1px solid rgba(26,74,92,0.12)', borderRadius: 14, marginBottom: 32 }}>
                <span style={{ color: '#1a4a5c', flexShrink: 0, marginTop: 1 }}><IconCheck /></span>
                <p style={{ fontSize: 13, lineHeight: 1.6, color: '#1a4a5c', fontWeight: 500 }}>{features[activeTab].note}</p>
              </div>

              <a
                href="#register"
                style={{ display: 'inline-flex', alignItems: 'center', gap: 8, backgroundColor: '#1a4a5c', color: '#faf6f0', padding: '13px 26px', borderRadius: 999, fontSize: 14, fontWeight: 700, textDecoration: 'none', transition: 'opacity 0.2s' }}
                onMouseEnter={e => (e.currentTarget.style.opacity = '0.82')}
                onMouseLeave={e => (e.currentTarget.style.opacity = '1')}
              >
                Get Early Access <IconArrow />
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* ══ CTA STRIPE ══════════════════════════════════ */}
      <section style={{ padding: '56px 24px', backgroundColor: '#d4820a' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'flex', flexWrap: 'wrap', gap: 24, alignItems: 'center', justifyContent: 'space-between' }}>
          <div>
            <h3 style={{ fontFamily: 'Fraunces, serif', fontSize: 28, fontWeight: 600, color: '#fff', marginBottom: 4 }}>
              Give your dog the care they deserve.
            </h3>
            <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.82)' }}>Early access is free. Registration takes 2 minutes.</p>
          </div>
          <a
            href="#register"
            style={{ display: 'inline-flex', alignItems: 'center', gap: 8, backgroundColor: '#fff', color: '#d4820a', padding: '13px 26px', borderRadius: 999, fontSize: 14, fontWeight: 700, textDecoration: 'none', flexShrink: 0, transition: 'transform 0.2s' }}
            onMouseEnter={e => (e.currentTarget.style.transform = 'scale(1.05)')}
            onMouseLeave={e => (e.currentTarget.style.transform = 'scale(1)')}
          >
            Register Now <IconArrow />
          </a>
        </div>
      </section>

      {/* ══ REGISTRATION ════════════════════════════════ */}
      <section id="register" style={{ padding: '96px 0', backgroundColor: '#0f2e38' }}>
        <div style={{ maxWidth: 760, margin: '0 auto', padding: '0 24px' }}>
          <div style={{ textAlign: 'center', marginBottom: 48 }}>
            <p style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', color: '#d4820a', marginBottom: 14 }}>Registration</p>
            <h2 style={{ fontFamily: 'Fraunces, serif', fontSize: 'clamp(32px, 4vw, 48px)', fontWeight: 600, color: '#faf6f0', marginBottom: 16 }}>
              Join Herdwise
            </h2>
            <p style={{ fontSize: 15, lineHeight: 1.7, color: 'rgba(250,246,240,0.62)', maxWidth: 420, margin: '0 auto' }}>
              Register below for early access. We don't store your data ourselves — responses go directly to our secure Google Form.
            </p>
          </div>

          <div style={{ borderRadius: 24, overflow: 'hidden', border: '1px solid rgba(250,246,240,0.1)', backgroundColor: 'rgba(250,246,240,0.04)' }}>
            <div style={{ padding: 8 }}>
              <iframe
                src={GOOGLE_FORM_URL}
                width="100%"
                height="740"
                frameBorder="0"
                marginHeight={0}
                marginWidth={0}
                title="Herdwise Dog Wellness Registration Form"
                style={{ display: 'block', borderRadius: 18, backgroundColor: '#fff' }}
              >
                Loading registration form…
              </iframe>
            </div>
          </div>

          <p style={{ textAlign: 'center', marginTop: 20, fontSize: 12, color: 'rgba(250,246,240,0.32)' }}>
            Responses are collected via Google Forms. We never sell your information.
          </p>
        </div>
      </section>

      {/* ══ FOOTER ══════════════════════════════════════ */}
      <footer style={{ backgroundColor: '#081820', borderTop: '1px solid rgba(250,246,240,0.06)', padding: '32px 24px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', display: 'flex', flexWrap: 'wrap', gap: 20, alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{ width: 32, height: 32, borderRadius: '50%', backgroundColor: '#1a4a5c', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#faf6f0' }}>
              <PawLogo />
            </div>
            <span style={{ fontFamily: 'Fraunces, serif', fontSize: 15, fontWeight: 600, color: '#faf6f0' }}>Herdwise Animal Wellness</span>
          </div>
          <div style={{ display: 'flex', gap: 28 }}>
            {navLinks.map(n => (
              <a key={n} href={`#${n.toLowerCase()}`} style={{ fontSize: 12, fontWeight: 500, color: 'rgba(250,246,240,0.4)', textDecoration: 'none', transition: 'color 0.2s' }}
                onMouseEnter={e => (e.currentTarget.style.color = '#d4820a')}
                onMouseLeave={e => (e.currentTarget.style.color = 'rgba(250,246,240,0.4)')}
              >{n}</a>
            ))}
          </div>
          <p style={{ fontSize: 11, color: 'rgba(250,246,240,0.28)' }}>© {new Date().getFullYear()} Herdwise. All rights reserved.</p>
        </div>
      </footer>

      {/* Mobile-only show/hide helpers via inline style tag */}
      <style>{`
        @media (max-width: 720px) {
          .hidden-mobile { display: none !important; }
          .show-mobile   { display: flex !important; }
        }
        @media (min-width: 721px) {
          .show-mobile { display: none !important; }
        }
      `}</style>
    </div>
  )
}
